# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Quote.create!(person: "John Lennon", quote: "There are two basic motivating forces: fear and love. When we are afraid, we pull back from life. When we are in love, we open to all that life has to offer with passion, excitement, and acceptanc")
Quote.create!(person: "John Lennon", quote: "Time you enjoy wasting, was not wasted.")
Quote.create!(person: "John Lennon", quote: "If everyone demanded peace instead of another television set, then there’d be peace")
Quote.create!(person: "John Lennon", quote: "We live in a world where we have to hide to make love, while violence is practiced in broad daylight.")
Quote.create!(person: "John Lennon", quote: "Reality leaves a lot to the imagination.")
Quote.create!(person: "John Lennon", quote: "When I was 5 years old, my mother always told me that happiness was the key to life. When I went to school, they asked me what I wanted to be when I grew up. I wrote down ‘happy’. They told me I didn’t understand the assignment, and I told them they didn’t understand life")
Quote.create!(person: "John Lennon", quote: "Turn off your mind, relax, and float downstream.")
Quote.create!(person: "John Lennon", quote: "I believe in everything until it’s disproved. So I believe in fairies, the myths, dragons. It all exists, even if it’s in your mind. Who’s to say that dreams and nightmares aren’t as real as the here and now?")
Quote.create!(person: "John Lennon", quote: "Everything will be okay in the end. If it’s not okay, it’s not the end.")
Quote.create!(person: "John Lennon", quote: "We’ve got this gift of love, but love is like a precious plant. You can’t just accept it and leave it in the cupboard or just think it’s going to get on by itself. You’ve got to keep watering it. You’ve got to really look after it and nurture it.")
Quote.create!(person: "John Lennon", quote: "Peace is not something you wish for; It’s something you make, something you do, something you are, and something you give away.")
Quote.create!(person: "John Lennon", quote: "I believe that what people call God is something in all of us. I believe that what Jesus and Mohammed and Buddha and all the rest said was right. It’s just that the translations have gone wrong.")
Quote.create!(person: "John Lennon", quote: "When you do something beautiful and nobody noticed, do not be sad. For the sun, every morning is a beautiful spectacle and yet most of the audience still sleeps.")
Quote.create!(person: "John Lennon", quote: "It matters not who you love, where you love, why you love, when you love or how you love, it matters only that you love")
Quote.create!(person: "John Lennon", quote: "We need to learn to love ourselves first, in all our glory and our imperfections. If we cannot love ourselves, we cannot fully open to our ability to love others or our potential to create. Evolution and all hopes for a better world rest in the fearlessness and open-hearted vision of people who embrace life.")
Quote.create!(person: "John Lennon", quote: "I’m not going to change the way I look or the way I feel to conform to anything. I’ve always been a freak. So I’ve been a freak all my life and I have to live with that, you know. I’m one of those people.")
Quote.create!(person: "John Lennon", quote: "If everyone could just be happy with themselves and the choices people around them make, the world would instantly be a better place!")
Quote.create!(person: "John Lennon", quote: "Declare it. Just the same way we declare war. That is how we will have peace… we just need to declare it.")
Quote.create!(person: "John Lennon", quote: "Count your age by friends, not years. Count your life by smiles, not tears.")
Quote.create!(person: "John Lennon", quote: "A dream you dream alone is only a dream. A dream you dream together is reality.")
Quote.create!(person: "John Lennon", quote: "Being honest may not get you a lot of friends but it’ll always get you the right ones.")
Quote.create!(person: "John Lennon", quote: "Love is a promise, love is a souvenir, once given never forgotten, never let it disappear")
Quote.create!(person: "John Lennon", quote: "Everybody loves you when you’re six foot in the ground.")
Quote.create!(person: "John Lennon", quote: "You don’t need anybody to tell you who you are or what you are. You are what you are!")
Quote.create!(person: "John Lennon", quote: "Trying to please everybody is impossible – if you did that, you’d end up in the middle with nobody liking you. You’ve just got to make the decision about what you think is your best, and do it")
Quote.create!(person: "John Lennon", quote: "A mistake is only an error, it becomes a mistake when you fail to correct it.")
Quote.create!(person: "John Lennon", quote: "Our society is run by insane people for insane objectives. I think we’re being run by maniacs for maniacal ends and I think I’m liable to be put away as insane for expressing that. That’s what’s insane about it")
Quote.create!(person: "John Lennon", quote: "As usual, there is a great woman behind every idiot.")
Quote.create!(person: "John Lennon", quote: "There’s nowhere you can be that isn’t where you’re meant to be…")
Quote.create!(person: "John Lennon", quote: "One thing you can’t hide – is when you’re crippled inside.")
Quote.create!(person: "John Lennon", quote: "It’s better to fade away like an old soldier than to burn out.")
Quote.create!(person: "John Lennon", quote: "There are no problems, only solutions.")
Quote.create!(person: "John Lennon", quote: "Love is all you need.")
Quote.create!(person: "John Lennon", quote: "Surrealism had a great effect on me because then I realized that the imagery in my mind wasn’t insanity. Surrealism to me is reality.")
Quote.create!(person: "John Lennon", quote: "For those of you in the cheap seats I’d like ya to clap your hands to this one; the rest of you can just rattle your jewelry!")
Quote.create!(person: "John Lennon", quote: "How can I go forward when I don’t know which way I’m facing?")
Quote.create!(person: "John Lennon", quote: "My role in society, or any artist’s or poet’s role, is to try and express what we all feel. Not to tell people how to feel. Not as a preacher, not as a leader, but as a reflection of us all")
Quote.create!(person: "John Lennon", quote: "Nobody controls me. I’m uncontrollable. The only one who controls me is me, and that’s just barely possible.")
Quote.create!(person: "John Lennon", quote: "What we’ve got to do is keep hope alive. Because without it we’ll sink.")
Quote.create!(person: "John Lennon", quote: "Everything is as important as everything else.")
Quote.create!(person: "John Lennon", quote: "If someone thinks that peace and love are just a cliche that must have been left behind in the 60s, that’s a problem. Peace and love are eternal")
Quote.create!(person: "John Lennon", quote: "There’s nothing you can know that isn’t known.")
Quote.create!(person: "John Lennon", quote: "Only by trying on other people’s clothes do we find what size we are.")
Quote.create!(person: "John Lennon", quote: "Produce your own dream. It’s quite possible to do anything, but not if you put it on the leaders and the parking meters.")
Quote.create!(person: "John Lennon", quote: "I don’t believe in killing whatever the reason!")
Quote.create!(person: "John Lennon", quote: "You may say I’m a dreamer, but I’m not the only one. I hope someday you’ll join us, and the world will be as one.")
Quote.create!(person: "John Lennon", quote: "It’s weird not to be weird.")
Quote.create!(person: "John Lennon", quote: "Get out there and get peace, think peace, and live peace and breathe peace, and you’ll get it as soon as you like.")
Quote.create!(person: "John Lennon", quote: "When I cannot sing my heart, I can only speak my mind.")
Quote.create!(person: "John Lennon", quote: "Happiness is just how you feel when you don’t feel miserable.")
Quote.create!(person: "John Lennon", quote: "If you want peace, you won’t get it with violence.")

